name: Main workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      working-directory: ./weli_writer_android
      run: chmod +x gradlew

    - name: Run unit tests
      working-directory: ./weli_writer_android
      run: ./gradlew test

    - name: Generate Release APK
      working-directory: ./weli_writer_android
      run: ./gradlew assembleRelease
    
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      # ID used to access action output
      id: sign_app
      with:
        releaseDirectory: weli_writer_android/app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.STORE_KEY_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"
    
    - uses: actions/upload-artifact@master
      with:
        name: release.apk
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
    
    - uses: actions/upload-artifact@master
      with:
        name: mapping.txt
        path: weli_writer_android/app/build/outputs/mapping/release/mapping.txt
